#!/bin/bash
# 📋 IMMEDIATE ACTION ITEMS - When MySQL Installation Completes
# Copy and paste these commands one at a time as indicated

echo "🔍 Checking MySQL Installation..."
brew list | grep mysql

# If MySQL shows up above, proceed with:
echo ""
echo "✅ MySQL is installed!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 NEXT STEPS - Copy each command and run one by one"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

echo ""
echo "1️⃣  START MYSQL SERVICE"
echo "   Command:"
echo "   brew services start mysql"
echo ""
read -p "   Hit ENTER after running the command above ▶️ "

echo ""
echo "2️⃣  CREATE DATABASE & USER"
echo "   Command (paste entire block):"
echo "   mysql -u root << 'EOF'"
echo "   CREATE DATABASE resultspro_db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
echo "   CREATE USER 'resultspro_user'@'localhost' IDENTIFIED BY 'resultspro_pass';"
echo "   GRANT ALL PRIVILEGES ON resultspro_db.* TO 'resultspro_user'@'localhost';"
echo "   FLUSH PRIVILEGES;"
echo "   EOF"
echo ""
read -p "   Hit ENTER after database is created ▶️ "

echo ""
echo "3️⃣  VERIFY DATABASE CONNECTION"
echo "   Command:"
echo "   mysql -u resultspro_user -p 'resultspro_pass' -e \"SELECT database();\" resultspro_db"
echo ""
read -p "   Hit ENTER after verification (should print: resultspro_db) ▶️ "

echo ""
echo "4️⃣  BUILD BACKEND"
echo "   Commands:"
echo "   cd /Users/user/Desktop/ResultsPro/backend"
echo "   npm run build"
echo ""
read -p "   Hit ENTER after build completes (should show 0 TypeScript errors) ▶️ "

echo ""
echo "5️⃣  SYNC DATABASE SCHEMA"
echo "   Command:"
echo "   npm run db:sync"
echo ""
read -p "   Hit ENTER after sync completes ▶️ "

echo ""
echo "6️⃣  SEED TEST DATA"
echo "   Command:"
echo "   npm run db:seed"
echo ""
read -p "   Hit ENTER after seeding completes ▶️ "

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 NOW START THE SERVERS (Use 2 separate terminal windows/tabs)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

echo ""
echo ""
echo "🟦 TERMINAL 1: START BACKEND"
echo "┌─────────────────────────────────────────────────────────"
echo "│ cd /Users/user/Desktop/ResultsPro/backend"
echo "│ npm run dev"
echo "│"
echo "│ Expected output:"
echo "│ ✅ Server running at http://localhost:3000"
echo "└─────────────────────────────────────────────────────────"

echo ""
echo ""
echo "🟦 TERMINAL 2: START FRONTEND"
echo "┌─────────────────────────────────────────────────────────"
echo "│ cd /Users/user/Desktop/ResultsPro"
echo "│ npm run dev"
echo "│"
echo "│ Expected output:"
echo "│ ➜  Local: http://localhost:8080"
echo "└─────────────────────────────────────────────────────────"

echo ""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ DONE! YOU'RE ALL SET"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

echo ""
echo "🌐 OPEN YOUR BROWSER"
echo "   Go to: http://localhost:8080"
echo ""
echo "🧪 TEST THE SYSTEM"
echo "   Login with demo credentials:"
echo "   Email:    admin@demoschool.test"
echo "   Password: demo_password_123"
echo ""
echo "📊 OPTIONAL: RUN FULL TEST SUITE"
echo "   In a third terminal:"
echo "   cd /Users/user/Desktop/ResultsPro"
echo "   ./test-setup.sh"
echo ""
echo "🚀 READY TO DEPLOY?"
echo "   See: EC2_DEPLOYMENT.md"
echo ""
echo "📚 NEED HELP?"
echo "   See: README.md (Main index)"
echo "        DESIGN_SPECIFICATION.md (API docs)"
echo "        LOCAL_SETUP.md (Detailed setup)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
